---
- apt:
    name: 
      - python3
      - python3-pip
      - pwgen
      - openssl
      - apache2-utils
- pip:
    name:
      - PyNaCl
    executable: pip3
- set_fact:
    wsid_hooks_passwd_dir: "{{ wsid_etc }}/hooks/onpasswdchange"
    wsid_hooks_key_dir: "{{ wsid_etc }}/hooks/onkeychange"
    wsid_scripts_dir: "{{ wsid_etc }}/scripts"
- name: system directories
  file:
    dest: "{{ item }}"
    state: directory
  loop:
    - "{{ wsid_hooks_passwd_dir }}"
    - "{{ wsid_hooks_key_dir }}"
    - "{{ wsid_scripts_dir }}"
    - "{{ wsid_includes_dir }}"
- set_fact:
    wsid_script_setup: "{{ wsid_scripts_dir }}/setup.sh"
    wsid_script_teardown: "{{ wsid_scripts_dir }}/teardown.sh"
    wsid_script_rotate: "{{ wsid_scripts_dir }}/rotate.sh"
    wsid_script_expose_hostkey: "{{ wsid_scripts_dir }}/expose_hostkey.sh"
- name: systemd scripts
  template:
    dest: "{{ wsid_scripts_dir }}/{{ item }}"
    src: "{{ item }}"
    mode: 0744
  loop: [ "setup.sh", "teardown.sh", "rotate.sh" ]     
- name: systemd service unit
  template:
    dest: /etc/systemd/system/wsid.service
    src: wsid.service
  register: wsid_systemd_conf
- name:
  service:
    name: wsid
    daemon_reload: "{{ wsid_systemd_conf.changed }}"
    enabled: yes
    state: "{{ 'restarted' if wsid_systemd_conf.changed else 'started' }}"
- include: disabled_identity.yml
  loop: "{{ wsid_disabled_identities }}"
  loop_control:
    loop_var: wsid_identity
- cron:
    name: "WSID secrets rotation and publishing"
    job: "{{ wsid_script_rotate }} {{ wsid_identities | join(' ') }}"
    minute: "*/{{ wsid_rotation_minutes }}"
- name: nginx include snippet
  template:
    dest: "{{ wsid_includes_dir }}/nginx-expose.conf"
    src: nginx-expose.conf
